### ISSUE TITLE
UpdateVersion help

### ISSUE THREAD

**Issue by UnT7** [Hackndo/pyGPOAbuse#13]
Hello, I've been learning how to use GPOs recently. I'm trying to manually add policies for startup/shutdown and user login/logout. I manually created the startup directory and scripts.ini file, among other things. However, I'm facing difficulties in updating the version number and enabling script settings. Can I accomplish this step using pyGPOAbuse?

**Comment by Hackndo** [comment]
Hello,
You can use code from this project, but the project itself won't help you, as it updates lots of other stuff you don't want.

https://github.com/Hackndo/pyGPOAbuse/blob/63db4a415dad189c5762e6aff2d7bad2ac65039c/pygpoabuse/gpo.py#L79-L135
