### ISSUE TITLE
"Could not get versionNumber attribute" - "Error while updating versions"

### ISSUE THREAD

**Issue by jsdhasfedssad** [Hackndo/pyGPOAbuse#6]
I simply execute the below command. The user account has full access to the GPO. The GPO did not contain anything before this. My DC is running 2019.

<img width="1345" alt="gpo3" src="https://user-images.githubusercontent.com/97032878/208311484-654d1d34-c59e-409c-bdef-6f5e8f95f769.png">

Update. When this error occurs the scheduled task is created but the task within it is not executed. Probably because the value "Version" in the file GPT.ini is set to "0". This has the consequence that the target machine reads the GPO, I can see that in Responder, but ignores the task thinking there is nothing new to do.

This happens only for a newly created GPO. If I delete the initial scheduled task and then write it again using the exact same command as for the first time, there  is no error and the task is executed. The value "Version" in the file GPT.in has also been incremented to a value other than "0".

**Comment by Hackndo** [comment]
Fixed
